# Generated by Django 5.0.6 on 2024-05-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
    ]
